- cvprac/cvp_api.py
- test/system/test_cvp_api.py
Allows user to specify client get/post timeouts used by API calls. Issue #7
> Added request timeout instance variable to API.

- cvprac/cvp_api.py
> Make REST call to addTempAction before saveTopology.

- cvprac/cvp_api.py
- test/system/test_cvp_api.py
Add functions for getting container info and image info. Add functions for applying image bundles to devices/containers and removing image bundles from a container. Added or updated tests for all new functionality. Fixes #16
> Add base functions and tests for image interaction

- cvprac/cvp_api.py
- test/system/test_cvp_api.py
> Added base deploy_device function.

- cvprac/cvp_api.py
> Fix typo in data structure field name.

- cvprac/cvp_api.py
- cvprac/cvp_client.py
- test/system/test_cvp_client.py
> Add ability for user to configure log level.

- Jenkinsfile
- MANIFEST.in
- Makefile
- README.rst
- dev-requirements.txt
- pre-commit.sh
> Add Jenkins integration and pre-commit hook

- Makefile
- cvprac/cvp_api.py
- cvprac/cvp_client.py
- dev-requirements.txt
- test/system/test_cvp_api.py
- test/system/test_cvp_client.py
- test/unit/test_client.py
Fixed system tests and added some client unit tests.
Fixes #28
> Update client to default to https with http fallback.

- cvprac/cvp_api.py
- cvprac/cvp_client.py
- test/system/test_cvp_api.py
- test/unit/test_client.py
> Add property to CvpClient that stores the last node used to make a request to CVP.

- cvprac/cvp_api.py
Convert exception to string before check
> Fixes issue #36

- cvprac/cvp_api.py
> Add ability to specify a query parameter to get_inventory().

- cvprac/cvp_api.py
- test/system/test_cvp_api.py
> Fix get_devices_in_container to only return devices in the specified container. Also added system tests.

- README.rst
> Add contact info to docs.

- cvprac/cvp_api.py
- test/system/test_cvp_api.py
- add_device_to_inventory
- retry_add_to_inventory
- delete_device
- delete_devices
- get_non_connected_device_count
- save_inventory
> Add device add/delete to inventory

- cvprac/cvp_api.py
> Add fix for special characters in object names in url.

- cvprac/cvp_api.py
Add function to leverage snapshot/captureContainerLevelSnapshot.do? api.
> Add capture_ContainerLevelSnapshot Function

- cvprac/cvp_api.py
> Update urllib quote_plus usages to handle Python3.

- cvprac/cvp_api.py
> Add snapshot template key to task list entries for create change control method.

- cvprac/cvp_client.py
> Fix issue 61 where requests fail if response has no json payload.

- cvprac/cvp_api.py
> Fix issue85.

- cvprac/cvp_api.py
- test/system/test_cvp_api.py
> Add container configlet apply/remove methods

- cvprac/cvp_client.py
- test/system/test_cvp_client.py
> Add ability to set API request timeout via client connect method.

- cvprac/cvp_api.py
- test/system/test_cvp_api.py
> Add method and test for API endpoint /provisioning/v2/validateAndCompareConfiglets.do.

- cvprac/cvp_client.py
> Add general support for using api tokens for access to REST API.

- cvprac/cvp_api.py
Implement a new method to search device using serial number.
It is used to support feature in arista.cvp.cv_device_v3 where device will be identified by serial number instead of fqdn/hostname fields.
Required for [Ansible CVP PR #374](https://github.com/aristanetworks/ansible-cvp/pull/374)
> feat(api): Add method to search device by serial_number

- docs/labs/lab06-provisioning/mlag_issu.py
Adding MLAG ISSU example by https://github.com/mmaaloul
> Mlagissu example

- test/fixtures/cvp_nodes.yaml
- test/system/test_cvp_api.py
- test/system/test_cvp_base.py
- test/system/test_cvp_change_control_api.py
- test/system/test_cvp_client.py
- test/system/test_cvp_client_api.py
Adding change control test cases.
> Adding tests for change control apis

- README.md
The last document update introduced wrong links. That links are corrected in this PR.
> Doc: Correct the links in the documentation

- MANIFEST.in
- dev-requirements.txt
- setup.py
Add twine for dev requirements. Remove unused import from setup. Fix README in MANIFEST
> Dev tools updates

- test/lib/systestlib.py
- test/system/test_cvp_base.py
- test/system/test_cvp_client_api.py
> Test: Allow request_timeout and connect_timeout to be configurable for system test DUTs

- test/system/test_cvp_client_api.py
> Test: Allow wait times for long running workspace actions in test case

- cvprac/cvp_api.py
- test/system/test_cvp_client_api.py
Check if comments are OK or if we should add examples as well.
> Feat: Add functions for add_role, get_role, update_role and delete_role API endpoints

- cvprac/cvp_client.py
- requirements.txt
- setup.py
> Feat: Add proxy support

- cvprac/cvp_api.py
In the current version of cvprac the `device_decommissioning()` function uses `get_device_by_serial()` to check if the device exists in CloudVision however that API works strictly for provisioned devices, so if you have a device that is not provisioned you cannot decommission it and you'd get the following error
```python
>>> clnt.api.device_decommissioning(device_id, request_id)
2023-Jul-13 21:33:06 IST <WARNING> cvp_api device_decommissioning: Device with JPE19290408 serial number does not exist (or is not registered) to decommission
```
to improve on this instead of using `get_device_by_serial()`, I've used `get_inventory()`, however in its current state `get_inventory()` had the `provisioned` query parameter always set to True, so I've added a positional argument at the end of …
> Fix: ability to use device_decommissioning for unprovisioned devices

- cvprac/cvp_client.py
- test/system/test_cvp_client.py
Tested against CVP 2022.3.2 (old password change functionality) and 2022.3.1 (new password change functionality).
> Feat: Add v9.0 apiversion and handling of new password change logout functionality in 2023.1.0

- setup.py
> Fix: Update setup.py to reference python3 only.

- dev-requirements.txt
- test/unit/test_client.py
> Fix: Replace mock with unitest.mock for Py3

- cvprac/cvp_api.py
- test/system/test_cvp_client_api.py
> Feat: Add support for searchTopology V3 endpoint
