requirements.txt
setup.py

Ran into this as well, trying to install CvpRac from pip as well as from source.
logging is built in to current versions of python
Installing with pip causes problems due to old version of logging
being installed.
fixes #35

Remove requirements for logging module

---

cvprac/cvp_api.py
test/system/test_cvp_api.py

get_device_by_name should ensure that the FQDN of the returned device fully match the parameter.
Before this PR, if a device FQDN is contained in another device FQDN it can't be assured which one is returned.

Fix get_device_by_name to return only the device with the given FQDN

---

cvprac/cvp_api.py

The `'id': 1` key/value included in the data dictionaries passed to _add_temp_action causes CVP 2018 to give an error like
```
CvpApiError: POST: https://10.16.129.30:443/web/provisioning/addTempAction.do?format=topology&queryParam=&nodeId=root : Request Error: Input json is not compliant with schema. object instance has properties which are not allowed by the schema: ["id"]
```
It looks like this key is not required in 2017 versions either, but does not cause the failure seen in 2018.
I think this fixes #50, since deploy_device calls several methods that included this key/value in the data structure.
Testing was only done with cloud-deploy deployments for both 2017 and 2018.

Remove 'id': 1 from _add_temp_action data struct

---

cvprac/cvp_api.py

Modify get_device_by_name() to use cvprac get_inventory() function instead of duplicating api calls. #62 
This seems to work. Removed the urllib.quote_plus sanitization, since it's being injected on the query upstream in get_inventory().

Issue 62 patch

---

cvprac/cvp_api.py

Need to report task IDs from a customer script.

Allow waiting for task IDs when updating configlets

---

cvprac/cvp_api.py
cvprac/cvp_client.py
test/system/test_cvp_api.py

Fix issues with client that were causing system tests to fail.
Reformat client _make_request to fix Python 3 UnboundLocalError.
Fix system tests to put CVP node under test back into the state it was found in.
Add necessary API modules to allow tests to restore state of CVP node under test.
Assorted other updates for Python 3 support.

Finish Python 3 updates

---

cvprac/cvp_api.py

Add function add_devices_to_inventory to allow multiple devices to be added simultaneously. Helps speed up large deployments from cloud-deploy. Basically a multiple device version of the existing add_device_to_inventory.
In the v2 api, the call to inventory/devices sometimes takes a short while for the devices to actually appear in the inventory list. We need to wait for the devices to appear before we can move them to their respective containers.

Add multiple devices in one call

---

cvprac/cvp_api.py
cvprac/cvp_client.py
test/system/test_cvp_api.py

search_configlets: calls configlet/searchConfiglets.do and returns the result.
Update the set_version method to set the api version to v1 or v2 based on CVP version used. Previous method split the version string and compared each element, so 2019.1 elements were not *both* >2017 and >1, so it applied api v1. Use pkg_resources.parse_version instead, which handles minor versions and even -EFT tags well.

Add search_configlets method and update version test

---

cvprac/cvp_api.py
test/system/test_cvp_api.py

Adds a new api call to import configlet builders into CVP.  It will import a configlet builder with form data supplied or none.
Tests will add a CB with form data and without form data.

Rob configletbuilder

---

cvprac/cvp_client.py

CVPRAC is selecting the wrong API version as 2018.1.3 > 2018.1

CVPRAC using the wrong API version

---

cvprac/cvp_client.py
test/unit/test_client.py

Current code attempts a connection with https, and upon failure (eg: a mistake in the password) falls back to http. As a consequence:
- the initial error (why it failed in the first place) is lost. It makes the investigation process much difficult
- the password is sent unencrypted over the network.
Apparently the initial behavior of "defaulting to http" was a request for users of old CVP versions that were fine configuring their network devices over an unencrypted connection.
Fix it: remove this feature entirely.

Never fallback to HTTP in case of connection failure

---

cvprac/cvp_client.py

This is required for the existing configlet builder scripts using
cvprac to work with overlays which is a feature of hume (2021.2.0)
The changes are backward compatible.

cvprac: Mask localhost/127.0.0.1 with node ip for cb scripts

---

cvprac/cvp_api.py

This is the first time I have made any meaningful contribution to open source so I apologize if I am doing something wrong.
I started to add a new API method in order to update configlet builders called update_configlet_builder.  I noticed this was lacking and so far I have been manually doing it with CVP's API in my own scripts..  Simply doing an updateConfiglet API would cause it to be of type static and not builder.  I hope this is helpful
I haven't tested this yet as far as this project goes.  Please feel free to reach out to me or let me know if i messed anything up.

started to add api method update_configlet_builder

---

docs/labs/lab05-device-management/add_image_wo_tempaction.py

Adding an example for apply an image to a device without creating a tempAction but directly using the saveTopology call to avoid duplicate task creation when multiple saveTopology calls are being made at the same time by multiple scripts

labs: add example for saving topology with specific tempaction data

---

cvprac/cvp_api.py

Allow to search device by using hostname part of the FQDN and not the full FQDN field.
Tentative fix for #152 
```python
device_facts = self.__cv_client.api.get_device_by_name(fqdn=device.fqdn)
device_facts = self.__cv_client.api.get_device_by_name(fqdn=device.fqdn, search_field='fqdn')
device_facts = self.__cv_client.api.get_device_by_name(fqdn=device.fqdn, search_field='hostname')
```

feat(cvp_api): Add support for hostname search in get_device_by_name

---

docs/labs/lab06-provisioning/vc_task_retrigger.py

Added some things (listed below) to make the script more general purpose;
- Accepts arguments for username, password and cvp servers
- Handles unverified context for older python versions
- Triggers a compliance check at the beginning (may require a delay?)
- Won't attempt task generation for unregistered devices or devices in the undefined container
- Allows for string match filtering of the devices its going to try and update

Some enhancements to the task_retrigger script

---

docs/labs/lab02-inventory-operations/get_running_configs_by_time.py

Added simple example on how to use the compliance service API to get the RC of each device in the inventory at a specific time and write it to a file

get the running-config of devices at specified time

---

cvprac/cvp_api.py
docs/labs/lab06-provisioning/change_control_custom_rapi.py
docs/labs/lab06-provisioning/change_control_workflow_rapi.py

This PR is to add wrappers for the new [Change Control Resource APIs ](https://aristanetworks.github.io/cloudvision-apis/models/changecontrol.v1/)introduced in 2021.2.0
The following new functions were added:
- change_control_get_one
- change_controls_get_all
- change_control_approval_get_one
- change_control_approval_get_all
- change_control_approve
- change_control_delete
- change_control_create_with_custom_stages
- change_control_create_for_tasks
- change_control_start
- change_control_stop
- change_control_schedule
All functions have detailed docstrings
CC creation is possible either via `change_control_create_for_tasks` which can generate a CC based on a list of task and run them in series or parallel, or more complex CCs can be created with `change_control_create_with_custom_stages` …

Add cc rapi

---

docs/labs/lab06-provisioning/auto_reconcile_on_rc_change.py

in this example you can see how to reconcile the configuration of all out of configuration compliance devices

Example: Add example on how to automatically reconcile configurations

---

cvprac/cvp_api.py
docs/labs/lab07-aaa/delete_svc_account_created_by_user.py
test/system/test_cvp_client_api.py

Fixes #234 
Change `svc_account_get_one` and `svc_account_get_all` to use the status endpoints instead of the config endpoints
`AccountService/GetOne` and `AccountService/GetAll` instead of `AccountConfigeService/GetOne` and `AccountConfigService/GetAll`
this will gain us two extra key values:
- `created_by`: the user that created the service account
- `last_access`: the last time the service account accessed the system
this change should be transparent for users who've used these functions before as the return data has the same format + those 2 k,v pairs
- added system test as well to check for those 2 new keys

Fix: Use status endpoint instead of config endpoint for service account resource APIs

---

cvprac/cvp_api.py

Removed the check for 'parentContainerId' from reset_device() method to resolve issue #239 
Fixes #239

Refactor: Handling - "if get_parent_container_for_device() returns None" inside reset_device()

---

cvprac/cvp_api.py
test/system/test_cvp_client_api.py
test/unit/test_api.py

Adds a workaround for the case where CVP API splits warnings over several strings when validating
configuration that has both errors and warnings.
- add a sanitization method to cvp_api & pass validation reply through sanitization
- add unittests
- add sytemtests

Fix: Add workaround for CVP API validation config

---

cvprac/cvp_api.py
test/system/test_cvp_client_api.py

Currently when using `apply_configlets_to_device()` when `create_task=False` we actually just ommit saving topology, like a pre-staging operation, however if there are no diffs between designed-config and running-config, we should just do what the UI does and not generate a task at all by running validateAndCompareConfiglets.do and add `configCompareCount` dict into the addTempAction.do payload. If all keys in that dict, namely `new`, `mismatch` and `reconcile` are 0, the backend will not generate a task.

Feat: add support for config validation during config assign

---

cvprac/cvp_client.py
test/fixtures/cvp_nodes.yaml
test/system/test_cvp_client.py

At the moment, cvprac does not do any validation during `connect()` if `api_token` is given.
- Currently impacts the `ansible-cvp` collection : https://github.com/aristanetworks/ansible-cvp/issues/675
`connect()` does not raise any error for invalid, expired or incorrect token. Thus upstream packages are assuming tokens are valid, leading to errors down the line.
None
- Added a request to the cvpInfo that should only return 200 if the token is valid and working.
- Added system tests

FIX: Add check to connect() to ensure token works

---

cvprac/cvp_api.py

We forgot to add URL encoding for the single getUser.do API, we had it for getUsers.do
Before:
we'd get
```
CvpApiError: GET: https://192.0.2.79:443/web/user/getUser.do?userId=bob@abc.com : Request Error: Entity does not exist
```
instead of 
```
CvpApiError: GET: https://192.0.2.79:443/web/user/getUser.do?userId=bob%40abc.com : Request Error: Entity does not exist
```
or an actual response

Fix: missing url encoding for get_user()

---

cvprac/cvp_api.py
cvprac/cvp_client.py

On CVaaS we're migrating away from the /api/v3/services endpoints and moving everything to resource APIs, as part of one of the phases we've moved the enrollment endpoint from
`/api/v3/services/admin.Enrollment/AddEnrollmentToken`
to
`/api/resources/admin.Enrollment/AddEnrollmentToken`
the payload stayed the same with the exception that the `validFor` key only accepts seconds now, e.g. 86400s (where previously you could do '24h' or '60m';
we will also migrate on on-prem once we get to 2024.2.0 (we'll do a separate PR for that in a few months)

Fix: updating the enrollment endpoint for CVaaS

---

cvprac/cvp_api.py

Adding timeout option to get_configlets_and_mappers() due to some corner cases where the API call could take more than 30 seconds (default timeout) to return data when the system is busy

Fix: add timeout to get_configlets_and_mappers()

---

cvprac/cvp_api.py

Minor update to move version check for usage of searchTopology V3 to 2021.2

Fix: Move version that searchTopology V3 was added to CVP 2021.2
